[package]
name = "bmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }

# database
diesel = { version = "2.2.0", features = ["postgres", "time"] }
openssl-sys = { version = "0.9.102", features = [
	"vendored",
] } # static linking required
pq-sys = { version = "0.6.1", features = ["bundled"] } # static linking required

##################
# other utilities
##################
serde = { version = "1.0.203", features = ["derive"] }
time = { version = "0.3.36", features = ["local-offset", "macros", "serde"] }
# read settings from envorionment variables
dotenvy = "0.15.7"
# logging
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["json", "local-time"] }

[dev-dependencies]
# setup for tests
ctor = "0.2.8"
serial_test = "3.1.1"

[[bin]]
name = "serve"
path = "src/bin/serve.rs"
