[package]
name = "bmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = "0.2.0"

# database
diesel = { version = "2.2.0", features = ["postgres", "time"] }
diesel-async = { version = "0.4.1", features = [
	"async-connection-wrapper",
	"postgres",
	"deadpool",
] }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
openssl-sys = { version = "0.9.102", features = [
	"vendored",
] } # static linking required
pq-sys = { version = "0.6.1", features = ["bundled"] } # static linking required

##################
# other utilities
##################
rand = "0.8.5"
itertools = "0.13.0"
serde = { version = "1.0.203", features = ["derive"] }
time = { version = "0.3.36", features = ["local-offset", "macros", "serde"] }
percent-encoding = "2.3.1"
# search enhancement
pratt-gen = "0.1.0"
# read settings from the dotenv file
dotenvy = "0.15.7"
# logging
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
# async runtime
tokio = { version = "1.38.0", features = ["rt", "macros", "sync"] }
# error handling
anyhow = "1.0.86"
thiserror = "1.0.63"

[dev-dependencies]
# setup for tests
ctor = "0.2.8"
serial_test = { version = "3.1.1", features = ["file_locks"] }

[patch.crates-io]
diesel-async = { git = "https://github.com/weiznich/diesel_async.git", rev = "6437e59" }

[[bin]]
name = "serve"
path = "src/bin/serve.rs"
