services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bearmark
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5
