name: Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-rust-musl-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build 
      run: |
        export SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}
        export SCCACHE_REGION=${{ secrets.SCCACHE_REGION }}
        export SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
        export SCCACHE_S3_USE_SSL=${{ secrets.SCCACHE_S3_USE_SSL }}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo ">>> Print Sccache infos"
        sccache -s

        echo ">>> Build project"
        cargo build --target x86_64-unknown-linux-musl --release --verbose