name: Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-rust-musl-latest
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: bmm
        options: >-
          --health-cmd 'pg_isready -q -U postgres'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build 
      run: |
        export SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}
        export SCCACHE_REGION=${{ secrets.SCCACHE_REGION }}
        export SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
        export SCCACHE_S3_USE_SSL=${{ secrets.SCCACHE_S3_USE_SSL }}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo ">>> Print Sccache infos"
        sccache -s

        echo ">>> Setup environment"
        ./scripts/cli.sh install-diesel
        ./scripts/cli.sh setup

        export CARGO_BUILD_TARGET=x86_64-unknown-linux-musl 

        echo ">>> Build project"
        cargo build --release --verbose

        echo ">>> Run tests"
        ./scripts/cli.sh test

        echo ">>> Print Sccache infos"
        sccache -s
