name: Build Release Image

on:
  release:
    types:
      - published
env:
  CARGO_TERM_COLOR: always

jobs:
  build-image:
    runs-on: ubuntu-rust-musl-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          export SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}
          export SCCACHE_REGION=${{ secrets.SCCACHE_REGION }}
          export SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
          export SCCACHE_S3_USE_SSL=${{ secrets.SCCACHE_S3_USE_SSL }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo ">>> Print Sccache infos"
          sccache -s

          echo ">>> Build project"
          cargo build --target x86_64-unknown-linux-musl --release --verbose
          cp ./target/x86_64-unknown-linux-musl/release/bmm ./server

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ gitea.REPOSITORY_OWNER }}/${{ gitea.REPOSITORY }}:${{ gitea.REF_NAME }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ gitea.REPOSITORY_OWNER }}/${{ gitea.REPOSITORY }}:${{ gitea.REF_NAME }}
